version: '3.8'
services:
  app:
    build:
      context: .
    container_name: ecommerce_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ecommerce_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tk2gK7fbTm
      MYSQL_DATABASE: sql12750184
      MYSQL_USER: sql12750184
      MYSQL_PASSWORD: tk2gK7fbTm
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
